apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playhive-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    # GameHub (main app)
    - host: playhive.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gamehub-service
                port:
                  number: 80

    # Snake subdomain
    - host: snake.playhive.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snake-service
                port:
                  number: 80

    # 2048 subdomain
    - host: game2048.playhive.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game2048-service
                port:
                  number: 80
