apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gamehub-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gamehub-service
                port:
                  number: 80
          - path: /snake
            pathType: Prefix
            backend:
              service:
                name: snake-service
                port:
                  number: 80
          - path: /2048
            pathType: Prefix
            backend:
              service:
                name: game2048-service
                port:
                  number: 80
